# .github/workflows/docker-build.yaml

name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'Taskfile.yml'
      - 'example.env'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: meta
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          IMAGE=ghcr.io/${{ github.repository_owner }}/py-ddns
          echo "timestamp=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "full_sha=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Build and push image with tags
        run: |
          IMAGE=${{ steps.meta.outputs.image }}
          TIMESTAMP=${{ steps.meta.outputs.timestamp }}
          FULL_SHA=${{ steps.meta.outputs.full_sha }}

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Containerfile \
            --build-arg COMMIT_SHA=$FULL_SHA \
            --tag $IMAGE:latest \
            --tag $IMAGE:$TIMESTAMP \
            --push .
